# Generated by Django 3.2.5 on 2021-12-22 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='domicilio_persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deletec_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('colonia', models.CharField(max_length=255)),
                ('alcaldia', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('entidadFederativa', models.CharField(max_length=255)),
                ('codigoPostal', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Modelo tipo domicilio_persona',
                'verbose_name_plural': 'Modelo tipo domicilio_persona',
            },
        ),
        migrations.CreateModel(
            name='licencia_persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deletec_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('numeroLicencia', models.CharField(max_length=255)),
                ('vigencia', models.DateField(null=True)),
                ('tipoLicencia', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Modelo tipo licencia_persona',
                'verbose_name_plural': 'Modelo tipo licencia_persona',
            },
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deletec_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido1', models.CharField(max_length=255)),
                ('apellido2', models.CharField(max_length=255)),
                ('curp', models.CharField(max_length=255)),
                ('rfc', models.CharField(max_length=255)),
                ('cuip', models.CharField(max_length=255)),
                ('fechaNacimiento', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'Modelo tipo persona',
                'verbose_name_plural': 'Modelo tipo persona',
            },
        ),
        migrations.CreateModel(
            name='instructores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Creacion')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificacion')),
                ('deletec_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminacion')),
                ('activo', models.BooleanField(default=True)),
                ('persona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mision.persona')),
            ],
            options={
                'verbose_name': 'Modelo tipo domicilio_persona',
                'verbose_name_plural': 'Modelo tipo domicilio_persona',
            },
        ),
        migrations.CreateModel(
            name='Historicalpersona',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Creacion')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deletec_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminacion')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido1', models.CharField(max_length=255)),
                ('apellido2', models.CharField(max_length=255)),
                ('curp', models.CharField(max_length=255)),
                ('rfc', models.CharField(max_length=255)),
                ('cuip', models.CharField(max_length=255)),
                ('fechaNacimiento', models.DateField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Modelo tipo persona',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicallicencia_persona',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Creacion')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deletec_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminacion')),
                ('numeroLicencia', models.CharField(max_length=255)),
                ('vigencia', models.DateField(null=True)),
                ('tipoLicencia', models.CharField(max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Modelo tipo licencia_persona',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Historicaldomicilio_persona',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Creacion')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificacion')),
                ('deletec_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminacion')),
                ('colonia', models.CharField(max_length=255)),
                ('alcaldia', models.CharField(max_length=255)),
                ('municipio', models.CharField(max_length=255)),
                ('entidadFederativa', models.CharField(max_length=255)),
                ('codigoPostal', models.CharField(max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Modelo tipo domicilio_persona',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
